using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DeepSigma.Mathematics.AutoDiff.Generator;

/// <summary>
/// Roslyn incremental source generator that emits <c>Grad_Foo</c> gradient wrappers for
/// methods annotated with <c>[Differentiable]</c>.
/// </summary>
/// <remarks>
/// The annotated method accepts <c>Var&lt;T&gt;</c> parameters (reverse mode) or
/// <c>DualNumber&lt;T&gt;</c> parameters (forward mode) and returns the same type.
/// The generator emits a same-class <c>Grad_Foo</c> sibling that accepts plain <c>T</c>
/// parameters, drives the tape or dual-number seeding internally, and returns the gradient
/// as a scalar <c>T</c> (single parameter) or a named value tuple of <c>T</c> components
/// (multiple parameters).
/// <para>
/// Diagnostic rules <c>AD001</c>–<c>AD008</c> are reported as errors at the annotated method site
/// for any configuration that the generator cannot handle; see <see cref="Diagnostics"/> for details.
/// </para>
/// </remarks>
[Generator]
public sealed class DifferentiableGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace DeepSigma.Mathematics.AutoDiff
        {
            public enum DiffMode { Reverse, Forward }

            [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false)]
            public sealed class DifferentiableAttribute : System.Attribute
            {
                public DiffMode Mode { get; set; } = DiffMode.Reverse;
            }
        }
        """;

    private const string VarTypeName = "DeepSigma.Mathematics.AutoDiff.Reverse.Var<T>";
    private const string DualTypeName = "DeepSigma.Mathematics.AutoDiff.Forward.DualNumber<T>";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject the [Differentiable] attribute and DiffMode enum into every compilation
        // so consumers do not need a separate attribute package reference.
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("DifferentiableAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var results = context.SyntaxProvider.ForAttributeWithMetadataName(
            "DeepSigma.Mathematics.AutoDiff.DifferentiableAttribute",
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, _) => Analyze(ctx));

        context.RegisterSourceOutput(results, static (spc, result) =>
        {
            foreach (var d in result.Diagnostics)
                spc.ReportDiagnostic(d.ToDiagnostic());
            if (result.Target is { } target)
                Emit(spc, target);
        });
    }

    /// <summary>
    /// Validates a single <c>[Differentiable]</c>-annotated method and, if valid, returns
    /// the <see cref="Target"/> descriptor used by the emit step.
    /// All diagnostic failures are collected and returned alongside a <see langword="null"/> target.
    /// </summary>
    private static AnalysisResult Analyze(GeneratorAttributeSyntaxContext ctx)
    {
        var diagnostics = new List<DiagnosticInfo>();

        if (ctx.TargetSymbol is not IMethodSymbol method)
            return new AnalysisResult(null, ImmutableArray<DiagnosticInfo>.Empty);

        var owner = method.ContainingType;
        var methodLocation = LocationInfo.From(method);

        // AD001: must be static
        if (!method.IsStatic)
            diagnostics.Add(new DiagnosticInfo(Diagnostics.MustBeStatic, methodLocation, method.Name));

        // AD002: container must be partial
        var anyPartial = owner.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(s => s.Modifiers.Any(m => m.ValueText == "partial"));
        if (!anyPartial)
            diagnostics.Add(new DiagnosticInfo(Diagnostics.ContainerMustBePartial, methodLocation, owner.Name, method.Name));

        // AD003: must have parameters
        if (method.Parameters.Length == 0)
        {
            diagnostics.Add(new DiagnosticInfo(Diagnostics.MustHaveParameters, methodLocation, method.Name));
            return new AnalysisResult(null, diagnostics.ToImmutableArray());
        }

        // Parameter shape checks
        string? mode = null;
        string? elementType = null;
        var paramNames = ImmutableArray.CreateBuilder<string>();
        bool paramsOk = true;

        foreach (var p in method.Parameters)
        {
            if (p.RefKind != RefKind.None)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.RefOrOutNotSupported, LocationInfo.From(p), p.Name, method.Name));
                paramsOk = false;
                continue;
            }

            if (p.Type is not INamedTypeSymbol named || named.TypeArguments.Length != 1)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.UnsupportedParameterType, LocationInfo.From(p),
                    p.Name, method.Name, p.Type.ToDisplayString()));
                paramsOk = false;
                continue;
            }

            var ctor = named.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string? thisMode = ctor switch
            {
                "global::DeepSigma.Mathematics.AutoDiff.Reverse.Var<T>" => "Reverse",
                "global::DeepSigma.Mathematics.AutoDiff.Forward.DualNumber<T>" => "Forward",
                _ => null
            };

            if (thisMode is null)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.UnsupportedParameterType, LocationInfo.From(p),
                    p.Name, method.Name, p.Type.ToDisplayString()));
                paramsOk = false;
                continue;
            }

            if (mode is null) mode = thisMode;
            else if (mode != thisMode)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.MixedParameterModes, methodLocation, method.Name));
                paramsOk = false;
            }

            var thisElement = named.TypeArguments[0].ToDisplayString();
            if (elementType is null) elementType = thisElement;
            else if (elementType != thisElement)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.InconsistentElementType, methodLocation,
                    method.Name, elementType, thisElement));
                paramsOk = false;
            }

            paramNames.Add(p.Name);
        }

        // AD008: declared Mode vs. inferred mode mismatch
        var declaredMode = ReadModeFromAttribute(ctx);
        if (paramsOk && mode is not null && declaredMode is not null && declaredMode != mode)
            diagnostics.Add(new DiagnosticInfo(Diagnostics.ModeMismatch, methodLocation, method.Name, declaredMode, mode));

        if (!paramsOk || mode is null || elementType is null || !method.IsStatic || !anyPartial)
            return new AnalysisResult(null, diagnostics.ToImmutableArray());

        var target = new Target(
            Namespace: owner.ContainingNamespace.IsGlobalNamespace ? null : owner.ContainingNamespace.ToDisplayString(),
            ClassName: owner.Name,
            ClassKeyword: owner.IsRecord ? "record" : (owner.TypeKind == TypeKind.Struct ? "struct" : "class"),
            IsStatic: owner.IsStatic,
            MethodName: method.Name,
            ElementType: elementType,
            ParamNames: paramNames.ToImmutable(),
            Mode: mode);

        return new AnalysisResult(target, diagnostics.ToImmutableArray());
    }

    /// <summary>
    /// Reads the explicit <c>Mode</c> property from the <c>[Differentiable]</c> attribute, if present.
    /// Returns <see langword="null"/> when the attribute does not specify a mode (defaulting to Reverse).
    /// </summary>
    private static string? ReadModeFromAttribute(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.Attributes.Length == 0) return null;
        foreach (var na in ctx.Attributes[0].NamedArguments)
            if (na.Key == "Mode" && na.Value.Value is int v)
                return v == 1 ? "Forward" : "Reverse";
        return null;
    }

    /// <summary>
    /// Writes the generated source file for a validated <see cref="Target"/>,
    /// delegating to <see cref="EmitReverse"/> or <see cref="EmitForward"/> based on the detected mode.
    /// </summary>
    private static void Emit(SourceProductionContext spc, Target t)
    {
        var methodBody = t.Mode == "Reverse" ? EmitReverse(t) : EmitForward(t);
        var nsBlock    = t.Namespace is not null ? $"namespace {t.Namespace};\n\n" : "";
        var staticMod  = t.IsStatic ? "static " : "";

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            using DeepSigma.Mathematics.AutoDiff.Reverse;
            using DeepSigma.Mathematics.AutoDiff.Forward;

            {{nsBlock}}{{staticMod}}partial {{t.ClassKeyword}} {{t.ClassName}}
            {
            {{methodBody}}}

            """;

        spc.AddSource($"{t.ClassName}_{t.MethodName}_Grad.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    /// <summary>
    /// Emits a <c>Grad_Foo</c> method body that uses a reverse-mode <c>ComputationTape</c>
    /// to compute all input gradients in a single backward pass.
    /// Returns a scalar <c>T</c> for single-parameter methods or a named value tuple for multi-parameter methods.
    /// </summary>
    private static string EmitReverse(Target t)
    {
        var n = t.ParamNames.Length;
        var T = t.ElementType;
        var gradName   = StripSuffix(t.MethodName);
        var returnType = n == 1 ? T
            : "(" + string.Join(", ", t.ParamNames.Select(p => $"{T} d{p}")) + ")";
        var paramList  = string.Join(", ", t.ParamNames.Select(p => $"{T} {p}"));
        var varDecls   = string.Join("\n        ",
            t.ParamNames.Select((p, i) => $"var __v{i} = __tape.Variable({p}, \"{p}\");"));
        var args       = string.Join(", ", Enumerable.Range(0, n).Select(i => $"__v{i}"));
        var returnExpr = n == 1 ? "__v0.Gradient"
            : "(" + string.Join(", ", Enumerable.Range(0, n).Select(i => $"__v{i}.Gradient")) + ")";

        return $$"""
                public static {{returnType}} Grad_{{gradName}}({{paramList}})
                {
                    using var __tape = ComputationTapePool<{{T}}>.Rent();
                    {{varDecls}}
                    var __result = {{t.MethodName}}({{args}});
                    __tape.Backward(__result);
                    return {{returnExpr}};
                }

            """;
    }

    /// <summary>
    /// Emits a <c>Grad_Foo</c> method body that uses forward-mode dual numbers,
    /// running one pass per input variable with a unit seed vector to collect all partial derivatives.
    /// Returns a scalar <c>T</c> for single-parameter methods or a named value tuple for multi-parameter methods.
    /// </summary>
    private static string EmitForward(Target t)
    {
        var n = t.ParamNames.Length;
        var T = t.ElementType;
        var gradName   = StripSuffix(t.MethodName);
        var returnType = n == 1 ? T
            : "(" + string.Join(", ", t.ParamNames.Select(p => $"{T} d{p}")) + ")";
        var paramList   = string.Join(", ", t.ParamNames.Select(p => $"{T} {p}"));
        var (one, zero) = LiteralsFor(T);
        var dualDecls   = string.Join("\n            ",
            t.ParamNames.Select((p, i) =>
                $"var __d{i} = new DualNumber<{T}>({p}, __i == {i} ? {one} : {zero});"));
        var dualArgs    = string.Join(", ", Enumerable.Range(0, n).Select(i => $"__d{i}"));
        var entries     = n == 1 ? "__grad[0]"
            : "(" + string.Join(", ", Enumerable.Range(0, n).Select(i => $"__grad[{i}]")) + ")";

        return $$"""
                public static {{returnType}} Grad_{{gradName}}({{paramList}})
                {
                    {{T}}[] __grad = new {{T}}[{{n}}];
                    for (int __i = 0; __i < {{n}}; __i++)
                    {
                        {{dualDecls}}
                        __grad[__i] = {{t.MethodName}}({{dualArgs}}).Dual;
                    }
                    return {{entries}};
                }

            """;
    }

    /// <summary>
    /// Returns typed numeric literals for seeding dual numbers with 1 and 0.
    /// Avoids unnecessary casts for the common scalar types.
    /// </summary>
    private static (string one, string zero) LiteralsFor(string elemType) => elemType switch
    {
        "double" => ("1.0", "0.0"),
        "float" => ("1f", "0f"),
        "decimal" => ("1m", "0m"),
        _ => ($"(({elemType})1)", $"(({elemType})0)")
    };

    /// <summary>
    /// Strips the <c>_Differentiable</c> suffix from a method name if present,
    /// allowing methods to be named <c>Foo_Differentiable</c> to avoid collisions
    /// while the generated gradient wrapper is named <c>Grad_Foo</c>.
    /// </summary>
    private static string StripSuffix(string name)
    {
        const string suffix = "_Differentiable";
        return name.EndsWith(suffix) ? name.Substring(0, name.Length - suffix.Length) : name;
    }

    // ── Private supporting types ─────────────────────────────────────────────

    /// <summary>Pairs an optional emit target with any diagnostics collected during analysis.</summary>
    private sealed record AnalysisResult(Target? Target, ImmutableArray<DiagnosticInfo> Diagnostics);

    /// <summary>
    /// Captures everything the emit step needs about a single validated <c>[Differentiable]</c> method.
    /// </summary>
    private sealed record Target(
        /// <summary>The containing namespace, or <see langword="null"/> for the global namespace.</summary>
        string? Namespace,
        /// <summary>The simple name of the containing type.</summary>
        string ClassName,
        /// <summary>The type keyword: <c>class</c>, <c>struct</c>, or <c>record</c>.</summary>
        string ClassKeyword,
        /// <summary><see langword="true"/> when the containing type is declared <c>static</c>.</summary>
        bool IsStatic,
        /// <summary>The name of the annotated method (before suffix stripping).</summary>
        string MethodName,
        /// <summary>The fully-qualified scalar element type, e.g. <c>double</c>.</summary>
        string ElementType,
        /// <summary>Ordered list of parameter names, used to generate variable declarations and the return tuple.</summary>
        ImmutableArray<string> ParamNames,
        /// <summary><c>"Reverse"</c> or <c>"Forward"</c>, inferred from the parameter types.</summary>
        string Mode);
}

/// <summary>
/// Captures source location information for a Roslyn symbol in a form that can be stored
/// in an incremental pipeline step without retaining the full Roslyn object graph.
/// </summary>
internal sealed record LocationInfo(string FilePath, TextSpan TextSpan, LinePositionSpan LineSpan)
{
    /// <summary>Creates a <see cref="LocationInfo"/> from the primary source location of <paramref name="symbol"/>.</summary>
    public static LocationInfo From(ISymbol symbol)
    {
        var loc = symbol.Locations.FirstOrDefault() ?? Location.None;
        return new LocationInfo(
            loc.SourceTree?.FilePath ?? string.Empty,
            loc.SourceSpan,
            loc.GetLineSpan().Span);
    }

    /// <summary>Reconstructs a Roslyn <see cref="Location"/> from the stored path and span data.</summary>
    public Location ToLocation() => string.IsNullOrEmpty(FilePath)
        ? Location.None
        : Location.Create(FilePath, TextSpan, LineSpan);
}

/// <summary>
/// A serialisable descriptor for a diagnostic to report, decoupled from Roslyn's
/// <see cref="Diagnostic"/> type so it can be safely cached by the incremental pipeline.
/// </summary>
internal sealed record DiagnosticInfo(DiagnosticDescriptor Descriptor, LocationInfo Location, params object?[] Args)
{
    /// <summary>Materialises a Roslyn <see cref="Diagnostic"/> from this descriptor.</summary>
    public Diagnostic ToDiagnostic() => Diagnostic.Create(Descriptor, Location.ToLocation(), Args);

    /// <inheritdoc/>
    public bool Equals(DiagnosticInfo? other) =>
        other is not null && Descriptor.Id == other.Descriptor.Id && Location == other.Location
        && Args.SequenceEqual(other.Args);

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        unchecked
        {
            int h = Descriptor.Id.GetHashCode() * 31 + Location.GetHashCode();
            foreach (var a in Args) h = h * 31 + (a?.GetHashCode() ?? 0);
            return h;
        }
    }
}
