using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AutoDiff.Generator;

/// <summary>
/// Emits <c>Grad_Foo</c> wrappers for methods annotated with <c>[Differentiable]</c>.
/// The attributed method takes <c>Var&lt;T&gt;</c> (reverse) or <c>DualNumber&lt;T&gt;</c> (forward)
/// parameters and returns the same type. The generator emits a sibling that takes plain
/// <c>T</c> parameters, drives the tape/dual seeding, and returns the gradient tuple.
/// </summary>
[Generator]
public sealed class DifferentiableGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace AutoDiff
        {
            public enum DiffMode { Reverse, Forward }

            [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false)]
            public sealed class DifferentiableAttribute : System.Attribute
            {
                public DiffMode Mode { get; set; } = DiffMode.Reverse;
            }
        }
        """;

    private const string VarTypeName = "AutoDiff.Reverse.Var<T>";
    private const string DualTypeName = "AutoDiff.Forward.DualNumber<T>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("DifferentiableAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var results = context.SyntaxProvider.ForAttributeWithMetadataName(
            "AutoDiff.DifferentiableAttribute",
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, _) => Analyze(ctx));

        context.RegisterSourceOutput(results, static (spc, result) =>
        {
            foreach (var d in result.Diagnostics)
                spc.ReportDiagnostic(d.ToDiagnostic());
            if (result.Target is { } target)
                Emit(spc, target);
        });
    }

    private static AnalysisResult Analyze(GeneratorAttributeSyntaxContext ctx)
    {
        var diagnostics = new List<DiagnosticInfo>();

        if (ctx.TargetSymbol is not IMethodSymbol method)
            return new AnalysisResult(null, ImmutableArray<DiagnosticInfo>.Empty);

        var owner = method.ContainingType;
        var methodLocation = LocationInfo.From(method);

        // AD001: must be static
        if (!method.IsStatic)
            diagnostics.Add(new DiagnosticInfo(Diagnostics.MustBeStatic, methodLocation, method.Name));

        // AD002: container must be partial
        var anyPartial = owner.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(s => s.Modifiers.Any(m => m.ValueText == "partial"));
        if (!anyPartial)
            diagnostics.Add(new DiagnosticInfo(Diagnostics.ContainerMustBePartial, methodLocation, owner.Name, method.Name));

        // AD003: must have parameters
        if (method.Parameters.Length == 0)
        {
            diagnostics.Add(new DiagnosticInfo(Diagnostics.MustHaveParameters, methodLocation, method.Name));
            return new AnalysisResult(null, diagnostics.ToImmutableArray());
        }

        // Parameter shape checks
        string? mode = null;
        string? elementType = null;
        var paramNames = ImmutableArray.CreateBuilder<string>();
        bool paramsOk = true;

        foreach (var p in method.Parameters)
        {
            if (p.RefKind != RefKind.None)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.RefOrOutNotSupported, LocationInfo.From(p), p.Name, method.Name));
                paramsOk = false;
                continue;
            }

            if (p.Type is not INamedTypeSymbol named || named.TypeArguments.Length != 1)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.UnsupportedParameterType, LocationInfo.From(p),
                    p.Name, method.Name, p.Type.ToDisplayString()));
                paramsOk = false;
                continue;
            }

            var ctor = named.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string? thisMode = ctor switch
            {
                "global::AutoDiff.Reverse.Var<T>" => "Reverse",
                "global::AutoDiff.Forward.DualNumber<T>" => "Forward",
                _ => null
            };

            if (thisMode is null)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.UnsupportedParameterType, LocationInfo.From(p),
                    p.Name, method.Name, p.Type.ToDisplayString()));
                paramsOk = false;
                continue;
            }

            if (mode is null) mode = thisMode;
            else if (mode != thisMode)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.MixedParameterModes, methodLocation, method.Name));
                paramsOk = false;
            }

            var thisElement = named.TypeArguments[0].ToDisplayString();
            if (elementType is null) elementType = thisElement;
            else if (elementType != thisElement)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.InconsistentElementType, methodLocation,
                    method.Name, elementType, thisElement));
                paramsOk = false;
            }

            paramNames.Add(p.Name);
        }

        // AD008: declared Mode vs. detected mode mismatch
        var declaredMode = ReadModeFromAttribute(ctx);
        if (paramsOk && mode is not null && declaredMode is not null && declaredMode != mode)
            diagnostics.Add(new DiagnosticInfo(Diagnostics.ModeMismatch, methodLocation, method.Name, declaredMode, mode));

        if (!paramsOk || mode is null || elementType is null || !method.IsStatic || !anyPartial)
            return new AnalysisResult(null, diagnostics.ToImmutableArray());

        var target = new Target(
            Namespace: owner.ContainingNamespace.IsGlobalNamespace ? null : owner.ContainingNamespace.ToDisplayString(),
            ClassName: owner.Name,
            ClassKeyword: owner.IsRecord ? "record" : (owner.TypeKind == TypeKind.Struct ? "struct" : "class"),
            IsStatic: owner.IsStatic,
            MethodName: method.Name,
            ElementType: elementType,
            ParamNames: paramNames.ToImmutable(),
            Mode: mode);

        return new AnalysisResult(target, diagnostics.ToImmutableArray());
    }

    private static string? ReadModeFromAttribute(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.Attributes.Length == 0) return null;
        foreach (var na in ctx.Attributes[0].NamedArguments)
            if (na.Key == "Mode" && na.Value.Value is int v)
                return v == 1 ? "Forward" : "Reverse";
        return null;
    }

    private static void Emit(SourceProductionContext spc, Target t)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using AutoDiff.Reverse;");
        sb.AppendLine("using AutoDiff.Forward;");
        sb.AppendLine();

        if (t.Namespace is not null)
        {
            sb.Append("namespace ").Append(t.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        var staticMod = t.IsStatic ? "static " : "";
        sb.Append(staticMod).Append("partial ").Append(t.ClassKeyword).Append(' ').AppendLine(t.ClassName);
        sb.AppendLine("{");

        if (t.Mode == "Reverse")
            EmitReverse(sb, t);
        else
            EmitForward(sb, t);

        sb.AppendLine("}");

        var fileName = $"{t.ClassName}_{t.MethodName}_Grad.g.cs";
        spc.AddSource(fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitReverse(StringBuilder sb, Target t)
    {
        var n = t.ParamNames.Length;
        var T = t.ElementType;

        var returnType = n == 1
            ? T
            : "(" + string.Join(", ", t.ParamNames.Select(p => $"{T} d{p}")) + ")";
        var paramList = string.Join(", ", t.ParamNames.Select(p => $"{T} {p}"));

        var gradName = StripSuffix(t.MethodName);

        sb.Append("    public static ").Append(returnType).Append(" Grad_").Append(gradName)
          .Append('(').Append(paramList).AppendLine(")");
        sb.AppendLine("    {");
        sb.Append("        using var __tape = TapePool<").Append(T).AppendLine(">.Rent();");

        for (int i = 0; i < n; i++)
            sb.Append("        var __v").Append(i).Append(" = __tape.Variable(")
              .Append(t.ParamNames[i]).Append(", \"").Append(t.ParamNames[i]).AppendLine("\");");

        var args = string.Join(", ", Enumerable.Range(0, n).Select(i => $"__v{i}"));
        sb.Append("        var __result = ").Append(t.MethodName).Append('(').Append(args).AppendLine(");");
        sb.AppendLine("        __tape.Backward(__result);");

        var grads = string.Join(", ", Enumerable.Range(0, n).Select(i => $"__v{i}.Gradient"));
        if (n == 1)
            sb.Append("        return ").Append(grads).AppendLine(";");
        else
            sb.Append("        return (").Append(grads).AppendLine(");");
        sb.AppendLine("    }");
    }

    private static void EmitForward(StringBuilder sb, Target t)
    {
        var n = t.ParamNames.Length;
        var T = t.ElementType;

        var returnType = n == 1
            ? T
            : "(" + string.Join(", ", t.ParamNames.Select(p => $"{T} d{p}")) + ")";
        var paramList = string.Join(", ", t.ParamNames.Select(p => $"{T} {p}"));

        var gradName = StripSuffix(t.MethodName);

        sb.Append("    public static ").Append(returnType).Append(" Grad_").Append(gradName)
          .Append('(').Append(paramList).AppendLine(")");
        sb.AppendLine("    {");
        sb.Append("        ").Append(T).Append("[] __grad = new ").Append(T).Append('[').Append(n).AppendLine("];");
        sb.Append("        for (int __i = 0; __i < ").Append(n).AppendLine("; __i++)");
        sb.AppendLine("        {");

        var (one, zero) = LiteralsFor(T);
        for (int i = 0; i < n; i++)
            sb.Append("            var __d").Append(i).Append(" = new DualNumber<").Append(T)
              .Append(">(").Append(t.ParamNames[i]).Append(", __i == ").Append(i)
              .Append(" ? ").Append(one).Append(" : ").Append(zero).AppendLine(");");

        var args = string.Join(", ", Enumerable.Range(0, n).Select(i => $"__d{i}"));
        sb.Append("            __grad[__i] = ").Append(t.MethodName)
          .Append('(').Append(args).AppendLine(").Dual;");
        sb.AppendLine("        }");

        var entries = string.Join(", ", Enumerable.Range(0, n).Select(i => $"__grad[{i}]"));
        if (n == 1)
            sb.Append("        return ").Append(entries).AppendLine(";");
        else
            sb.Append("        return (").Append(entries).AppendLine(");");
        sb.AppendLine("    }");
    }

    private static (string one, string zero) LiteralsFor(string elemType) => elemType switch
    {
        "double" => ("1.0", "0.0"),
        "float" => ("1f", "0f"),
        "decimal" => ("1m", "0m"),
        _ => ($"(({elemType})1)", $"(({elemType})0)")
    };

    private static string StripSuffix(string name)
    {
        const string suffix = "_Differentiable";
        return name.EndsWith(suffix) ? name.Substring(0, name.Length - suffix.Length) : name;
    }

    private sealed record AnalysisResult(Target? Target, ImmutableArray<DiagnosticInfo> Diagnostics);

    private sealed record Target(
        string? Namespace,
        string ClassName,
        string ClassKeyword,
        bool IsStatic,
        string MethodName,
        string ElementType,
        ImmutableArray<string> ParamNames,
        string Mode);
}

internal sealed record LocationInfo(string FilePath, TextSpan TextSpan, LinePositionSpan LineSpan)
{
    public static LocationInfo From(ISymbol symbol)
    {
        var loc = symbol.Locations.FirstOrDefault() ?? Location.None;
        return new LocationInfo(
            loc.SourceTree?.FilePath ?? string.Empty,
            loc.SourceSpan,
            loc.GetLineSpan().Span);
    }

    public Location ToLocation() => string.IsNullOrEmpty(FilePath)
        ? Location.None
        : Location.Create(FilePath, TextSpan, LineSpan);
}

internal sealed record DiagnosticInfo(DiagnosticDescriptor Descriptor, LocationInfo Location, params object?[] Args)
{
    public Diagnostic ToDiagnostic() => Diagnostic.Create(Descriptor, Location.ToLocation(), Args);

    public bool Equals(DiagnosticInfo? other) =>
        other is not null && Descriptor.Id == other.Descriptor.Id && Location == other.Location
        && Args.SequenceEqual(other.Args);

    public override int GetHashCode()
    {
        unchecked
        {
            int h = Descriptor.Id.GetHashCode() * 31 + Location.GetHashCode();
            foreach (var a in Args) h = h * 31 + (a?.GetHashCode() ?? 0);
            return h;
        }
    }
}
