using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DeepSigma.Mathematics.AutoDiff.Generator;

/// <summary>
/// Emits <c>Grad_Foo</c> wrappers for methods annotated with <c>[Differentiable]</c>.
/// The attributed method takes <c>Var&lt;T&gt;</c> (reverse) or <c>DualNumber&lt;T&gt;</c> (forward)
/// parameters and returns the same type. The generator emits a sibling that takes plain
/// <c>T</c> parameters, drives the tape/dual seeding, and returns the gradient tuple.
/// </summary>
[Generator]
public sealed class DifferentiableGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace DeepSigma.Mathematics.AutoDiff
        {
            public enum DiffMode { Reverse, Forward }

            [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false)]
            public sealed class DifferentiableAttribute : System.Attribute
            {
                public DiffMode Mode { get; set; } = DiffMode.Reverse;
            }
        }
        """;

    private const string VarTypeName = "DeepSigma.Mathematics.AutoDiff.Reverse.Var<T>";
    private const string DualTypeName = "DeepSigma.Mathematics.AutoDiff.Forward.DualNumber<T>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("DifferentiableAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var results = context.SyntaxProvider.ForAttributeWithMetadataName(
            "DeepSigma.Mathematics.AutoDiff.DifferentiableAttribute",
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, _) => Analyze(ctx));

        context.RegisterSourceOutput(results, static (spc, result) =>
        {
            foreach (var d in result.Diagnostics)
                spc.ReportDiagnostic(d.ToDiagnostic());
            if (result.Target is { } target)
                Emit(spc, target);
        });
    }

    private static AnalysisResult Analyze(GeneratorAttributeSyntaxContext ctx)
    {
        var diagnostics = new List<DiagnosticInfo>();

        if (ctx.TargetSymbol is not IMethodSymbol method)
            return new AnalysisResult(null, ImmutableArray<DiagnosticInfo>.Empty);

        var owner = method.ContainingType;
        var methodLocation = LocationInfo.From(method);

        // AD001: must be static
        if (!method.IsStatic)
            diagnostics.Add(new DiagnosticInfo(Diagnostics.MustBeStatic, methodLocation, method.Name));

        // AD002: container must be partial
        var anyPartial = owner.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(s => s.Modifiers.Any(m => m.ValueText == "partial"));
        if (!anyPartial)
            diagnostics.Add(new DiagnosticInfo(Diagnostics.ContainerMustBePartial, methodLocation, owner.Name, method.Name));

        // AD003: must have parameters
        if (method.Parameters.Length == 0)
        {
            diagnostics.Add(new DiagnosticInfo(Diagnostics.MustHaveParameters, methodLocation, method.Name));
            return new AnalysisResult(null, diagnostics.ToImmutableArray());
        }

        // Parameter shape checks
        string? mode = null;
        string? elementType = null;
        var paramNames = ImmutableArray.CreateBuilder<string>();
        bool paramsOk = true;

        foreach (var p in method.Parameters)
        {
            if (p.RefKind != RefKind.None)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.RefOrOutNotSupported, LocationInfo.From(p), p.Name, method.Name));
                paramsOk = false;
                continue;
            }

            if (p.Type is not INamedTypeSymbol named || named.TypeArguments.Length != 1)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.UnsupportedParameterType, LocationInfo.From(p),
                    p.Name, method.Name, p.Type.ToDisplayString()));
                paramsOk = false;
                continue;
            }

            var ctor = named.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string? thisMode = ctor switch
            {
                "global::DeepSigma.Mathematics.AutoDiff.Reverse.Var<T>" => "Reverse",
                "global::DeepSigma.Mathematics.AutoDiff.Forward.DualNumber<T>" => "Forward",
                _ => null
            };

            if (thisMode is null)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.UnsupportedParameterType, LocationInfo.From(p),
                    p.Name, method.Name, p.Type.ToDisplayString()));
                paramsOk = false;
                continue;
            }

            if (mode is null) mode = thisMode;
            else if (mode != thisMode)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.MixedParameterModes, methodLocation, method.Name));
                paramsOk = false;
            }

            var thisElement = named.TypeArguments[0].ToDisplayString();
            if (elementType is null) elementType = thisElement;
            else if (elementType != thisElement)
            {
                diagnostics.Add(new DiagnosticInfo(Diagnostics.InconsistentElementType, methodLocation,
                    method.Name, elementType, thisElement));
                paramsOk = false;
            }

            paramNames.Add(p.Name);
        }

        // AD008: declared Mode vs. detected mode mismatch
        var declaredMode = ReadModeFromAttribute(ctx);
        if (paramsOk && mode is not null && declaredMode is not null && declaredMode != mode)
            diagnostics.Add(new DiagnosticInfo(Diagnostics.ModeMismatch, methodLocation, method.Name, declaredMode, mode));

        if (!paramsOk || mode is null || elementType is null || !method.IsStatic || !anyPartial)
            return new AnalysisResult(null, diagnostics.ToImmutableArray());

        var target = new Target(
            Namespace: owner.ContainingNamespace.IsGlobalNamespace ? null : owner.ContainingNamespace.ToDisplayString(),
            ClassName: owner.Name,
            ClassKeyword: owner.IsRecord ? "record" : (owner.TypeKind == TypeKind.Struct ? "struct" : "class"),
            IsStatic: owner.IsStatic,
            MethodName: method.Name,
            ElementType: elementType,
            ParamNames: paramNames.ToImmutable(),
            Mode: mode);

        return new AnalysisResult(target, diagnostics.ToImmutableArray());
    }

    private static string? ReadModeFromAttribute(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.Attributes.Length == 0) return null;
        foreach (var na in ctx.Attributes[0].NamedArguments)
            if (na.Key == "Mode" && na.Value.Value is int v)
                return v == 1 ? "Forward" : "Reverse";
        return null;
    }

    private static void Emit(SourceProductionContext spc, Target t)
    {
        var methodBody = t.Mode == "Reverse" ? EmitReverse(t) : EmitForward(t);
        var nsBlock    = t.Namespace is not null ? $"namespace {t.Namespace};\n\n" : "";
        var staticMod  = t.IsStatic ? "static " : "";

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            using DeepSigma.Mathematics.AutoDiff.Reverse;
            using DeepSigma.Mathematics.AutoDiff.Forward;

            {{nsBlock}}{{staticMod}}partial {{t.ClassKeyword}} {{t.ClassName}}
            {
            {{methodBody}}}

            """;

        spc.AddSource($"{t.ClassName}_{t.MethodName}_Grad.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    private static string EmitReverse(Target t)
    {
        var n = t.ParamNames.Length;
        var T = t.ElementType;
        var gradName   = StripSuffix(t.MethodName);
        var returnType = n == 1 ? T
            : "(" + string.Join(", ", t.ParamNames.Select(p => $"{T} d{p}")) + ")";
        var paramList  = string.Join(", ", t.ParamNames.Select(p => $"{T} {p}"));
        var varDecls   = string.Join("\n        ",
            t.ParamNames.Select((p, i) => $"var __v{i} = __tape.Variable({p}, \"{p}\");"));
        var args       = string.Join(", ", Enumerable.Range(0, n).Select(i => $"__v{i}"));
        var returnExpr = n == 1 ? "__v0.Gradient"
            : "(" + string.Join(", ", Enumerable.Range(0, n).Select(i => $"__v{i}.Gradient")) + ")";

        return $$"""
                public static {{returnType}} {{gradName}}({{paramList}})
                {
                    using var __tape = TapePool<{{T}}>.Rent();
                    {{varDecls}}
                    var __result = {{t.MethodName}}({{args}});
                    __tape.Backward(__result);
                    return {{returnExpr}};
                }

            """;
    }

    private static string EmitForward(Target t)
    {
        var n = t.ParamNames.Length;
        var T = t.ElementType;
        var gradName   = StripSuffix(t.MethodName);
        var returnType = n == 1 ? T
            : "(" + string.Join(", ", t.ParamNames.Select(p => $"{T} d{p}")) + ")";
        var paramList   = string.Join(", ", t.ParamNames.Select(p => $"{T} {p}"));
        var (one, zero) = LiteralsFor(T);
        var dualDecls   = string.Join("\n            ",
            t.ParamNames.Select((p, i) =>
                $"var __d{i} = new DualNumber<{T}>({p}, __i == {i} ? {one} : {zero});"));
        var dualArgs    = string.Join(", ", Enumerable.Range(0, n).Select(i => $"__d{i}"));
        var entries     = n == 1 ? "__grad[0]"
            : "(" + string.Join(", ", Enumerable.Range(0, n).Select(i => $"__grad[{i}]")) + ")";

        return $$"""
                public static {{returnType}} {{gradName}}({{paramList}})
                {
                    {{T}}[] __grad = new {{T}}[{{n}}];
                    for (int __i = 0; __i < {{n}}; __i++)
                    {
                        {{dualDecls}}
                        __grad[__i] = {{t.MethodName}}({{dualArgs}}).Dual;
                    }
                    return {{entries}};
                }

            """;
    }

    private static (string one, string zero) LiteralsFor(string elemType) => elemType switch
    {
        "double" => ("1.0", "0.0"),
        "float" => ("1f", "0f"),
        "decimal" => ("1m", "0m"),
        _ => ($"(({elemType})1)", $"(({elemType})0)")
    };

    private static string StripSuffix(string name)
    {
        const string suffix = "_Differentiable";
        return name.EndsWith(suffix) ? name.Substring(0, name.Length - suffix.Length) : name;
    }

    private sealed record AnalysisResult(Target? Target, ImmutableArray<DiagnosticInfo> Diagnostics);

    private sealed record Target(
        string? Namespace,
        string ClassName,
        string ClassKeyword,
        bool IsStatic,
        string MethodName,
        string ElementType,
        ImmutableArray<string> ParamNames,
        string Mode);
}

internal sealed record LocationInfo(string FilePath, TextSpan TextSpan, LinePositionSpan LineSpan)
{
    public static LocationInfo From(ISymbol symbol)
    {
        var loc = symbol.Locations.FirstOrDefault() ?? Location.None;
        return new LocationInfo(
            loc.SourceTree?.FilePath ?? string.Empty,
            loc.SourceSpan,
            loc.GetLineSpan().Span);
    }

    public Location ToLocation() => string.IsNullOrEmpty(FilePath)
        ? Location.None
        : Location.Create(FilePath, TextSpan, LineSpan);
}

internal sealed record DiagnosticInfo(DiagnosticDescriptor Descriptor, LocationInfo Location, params object?[] Args)
{
    public Diagnostic ToDiagnostic() => Diagnostic.Create(Descriptor, Location.ToLocation(), Args);

    public bool Equals(DiagnosticInfo? other) =>
        other is not null && Descriptor.Id == other.Descriptor.Id && Location == other.Location
        && Args.SequenceEqual(other.Args);

    public override int GetHashCode()
    {
        unchecked
        {
            int h = Descriptor.Id.GetHashCode() * 31 + Location.GetHashCode();
            foreach (var a in Args) h = h * 31 + (a?.GetHashCode() ?? 0);
            return h;
        }
    }
}
